import {test, expect} from '@playwright/test';
const GOAL = 'Build an ESP32 room monitor with temperature, humidity and an OLED.';
test('golden path: prompt, simulated verification, deliberate SDA failure, repair, retry', async ({page}) => {
  await page.goto('/build');
  await page.fill('#hero-goal', GOAL);
  await page.getByRole('button', {name: /Build it/}).click();
  await page.waitForURL(/\/project\//);
  await expect(page.locator('.school-status')).toContainText('Ready to learn', {timeout: 45000});
  await expect(page.locator('.react-flow__nodes')).toContainText('BME280');
  await page.getByRole('button', {name: /Run practice/}).click();
  await expect(page.getByText('This experiment passed its checks')).toBeVisible({timeout: 45000});
  await page.getByRole('button',{name:'Runtime & evidence'}).click();
  await expect(page.getByText('Model · no physical evidence').first()).toBeVisible();
  await page.getByRole('button',{name:'Close runtime'}).click();
  await page.getByRole('button', {name: /Try an SDA failure on the model/}).click();
  await expect(page.getByText('Let’s check the results')).toBeVisible({timeout: 45000});
  await expect(page.locator('.school-repair')).toContainText('Check & recover');
  await page.getByLabel(/I confirm the repair has been applied/).check();
  await page.getByRole('button', {name: /Repair & retest/}).click();
  await expect(page.getByText('This experiment passed its checks')).toBeVisible({timeout: 45000});
});
