import {test,expect,type Page} from '@playwright/test';
async function create(page:Page,goal='Build an ESP32 room monitor with temperature, humidity and an OLED.'){
 await page.goto('/build');await page.fill('#hero-goal',goal);await page.getByRole('button',{name:/Build it/}).click();await page.waitForURL(/\/project\//);await expect(page.locator('.flow-status')).toContainText('Contract valid',{timeout:45000});return page.url().split('/').at(-1)!;
}
async function current(page:Page,id:string){return page.evaluate(async id=>{const session=await(await fetch('/api/session')).json();return(await fetch('/api/projects/'+id,{headers:{'X-IOT-Session':session.token}})).json();},id);}
test('hardware graph drag and pan stay browser-local; eight cables and minimap persist',async({page})=>{
 const id=await create(page);await expect(page.locator('.react-flow__edge')).toHaveCount(8);await expect(page.getByLabel('Circuit map')).toBeVisible();const before=await current(page,id);
 const caption=page.locator('[data-id="bme280"] .hardware-part');const box=(await caption.boundingBox())!;await page.mouse.move(box.x+3,box.y+3);await page.mouse.down();await page.mouse.move(box.x+63,box.y+53,{steps:10});await page.mouse.up();
 await expect.poll(()=>page.evaluate(id=>localStorage.getItem('iot-flow-layout:'+id),id)).toContain('bme280');await page.waitForTimeout(1200);const after=await current(page,id);expect(after.contractId).toBe(before.contractId);expect(after.contracts.at(-1).hash).toBe(before.contracts.at(-1).hash);await expect(page.getByRole('button',{name:/Run practice/})).toBeEnabled();
 await page.reload();await expect(page.locator('.react-flow__edge')).toHaveCount(8);await expect(page.getByRole('button',{name:'＋ Parts'})).toBeVisible();
});
test('inspector edits gate all tabs; invalid wiring can be repaired with a new revision',async({page})=>{
 const id=await create(page);await page.locator('[data-id="bme280"]').click();await page.getByLabel('Connection bme280 SDA').selectOption('18');await expect(page.getByRole('button',{name:/Run practice/})).toBeDisabled();await page.getByRole('tab',{name:'Code',exact:true}).click();await expect(page.getByRole('button',{name:/Run practice/})).toBeDisabled();await page.getByRole('tab',{name:'Design',exact:true}).click();await page.getByRole('button',{name:'Apply wiring'}).click();await expect(page.locator('.flow-status')).toContainText('Contract blocked');await expect(page.getByRole('button',{name:/Run practice/})).toBeDisabled();
 await page.locator('[data-id="ssd1306"]').click();await page.getByLabel('Connection ssd1306 SDA').selectOption('18');await page.getByRole('button',{name:'Apply wiring'}).click();await expect(page.locator('.flow-status')).toContainText('Contract valid');await expect(page.getByRole('button',{name:/Run practice/})).toBeEnabled();expect((await current(page,id)).contracts.length).toBe(3);
});
test('pin handles connect; selected cable can be deleted and restored before apply',async({page})=>{
 await create(page);await page.locator('[data-id="bme280"]').click();await page.getByLabel('Connection bme280 SDA').selectOption('');await page.getByRole('button',{name:'Close inspector'}).click();const from=page.getByLabel('Pin esp32-devkit 21',{exact:true}),to=page.getByLabel('Pin bme280 SDA',{exact:true});const a=(await from.boundingBox())!,b=(await to.boundingBox())!;await page.mouse.move(a.x+a.width/2,a.y+a.height/2);await page.mouse.down();await page.mouse.move(b.x+b.width/2,b.y+b.height/2,{steps:15});await page.mouse.up();await expect(page.locator('.react-flow__edge')).toHaveCount(8);await expect(page.getByRole('button',{name:/Run practice/})).toBeEnabled();
 await page.getByRole('button',{name:'Close inspector'}).click();
 const point=await page.locator('[data-id="wire:bme280:SDA"] .react-flow__edge-path').evaluate((element)=>{const path=element as SVGPathElement;for(let step=1;step<20;step++){const p=path.getPointAtLength(path.getTotalLength()*step/20),matrix=path.getScreenCTM();if(!matrix)continue;const screen=new DOMPoint(p.x,p.y).matrixTransform(matrix);if(document.elementFromPoint(screen.x,screen.y)?.closest('[data-id]')?.getAttribute('data-id')==='wire:bme280:SDA')return{x:screen.x,y:screen.y};}return null;});expect(point).not.toBeNull();await page.mouse.click(point!.x,point!.y);
 await page.getByRole('button',{name:'Delete wire'}).click();await expect(page.locator('.react-flow__edge')).toHaveCount(7);await expect(page.getByRole('button',{name:/Run practice/})).toBeDisabled();await page.getByRole('button',{name:'Discard edits'}).click();await expect(page.locator('.react-flow__edge')).toHaveCount(8);
});
test('button assemblies expand faithful immutable internals and mobile drawers fit',async({page})=>{
 await create(page,'Buat tombol dan LED: tekan tombol maka indikator menyala.');await page.locator('[data-id="button-pullup-10k"]').click();await page.getByRole('button',{name:'Open assembly'}).click();await expect(page.locator('[data-id="button-pullup-10k::SW1"]')).toBeVisible();await expect(page.locator('[data-id="button-pullup-10k::R1"]')).toContainText('10kΩ');await expect(page.locator('.react-flow__edge')).toHaveCount(9);
 await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Close inspector'}).click();await page.getByRole('button',{name:'＋ Parts'}).click();await expect(page.getByLabel('Search parts')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);await page.getByRole('button',{name:'Close parts'}).click();await page.getByRole('button',{name:'Open chat'}).click();await expect(page.getByLabel('Message for the hardware engineer')).toBeVisible();
});
test('polling preserves dirty wiring and reports a concurrent revision conflict',async({page})=>{
 const id=await create(page);await page.getByRole('button',{name:'Inspect BME280 environmental sensor'}).click();await page.getByLabel('Connection bme280 SDA').selectOption('18');const initial=await current(page,id);
 const status=await page.evaluate(async({id,initial})=>{const session=await(await fetch('/api/session')).json();return(await fetch(`/api/projects/${id}/chat`,{method:'POST',headers:{'X-IOT-Session':session.token,'Content-Type':'application/json'},body:JSON.stringify({message:'Pindahkan SDA ke GPIO19.',purpose:'design',expectedContractId:initial.contractId,expectedDraftId:initial.activeDesign?.id??null})})).status;},{id,initial});expect(status).toBe(200);
 await expect(page.locator('.flow-status')).toContainText('Server revision changed',{timeout:30000});await expect(page.getByLabel('Connection bme280 SDA')).toHaveValue('18');await expect(page.getByRole('button',{name:'Apply wiring'})).toBeDisabled();await expect(page.getByRole('button',{name:/Run practice/})).toBeDisabled();await page.getByRole('button',{name:'Discard edits'}).click();await expect(page.getByLabel('Connection bme280 SDA')).toHaveValue('19');await expect(page.getByRole('button',{name:/Run practice/})).toBeEnabled();
});

test('planning LED retains manifest terminals and required series resistor',async({page})=>{
 await create(page);await page.getByRole('button',{name:'＋ Parts'}).click();await page.locator('.catalog-item').filter({hasText:'LED with 330Ω resistor'}).getByRole('button',{name:'Add',exact:true}).click();await page.getByRole('button',{name:'Close parts'}).click();
 await expect(page.locator('[data-id="led"]')).toBeVisible();await expect(page.getByLabel('Pin led ANODE',{exact:true})).toHaveCount(1);await expect(page.getByLabel('Pin led GND',{exact:true})).toHaveCount(1);await expect(page.locator('[data-id="led"]')).toContainText('330Ω series resistor required');await expect(page.getByRole('button',{name:/Run practice/})).toBeDisabled();
});

test('selected wire shines, identifies both endpoints, and rejects wrong supply before Apply',async({page})=>{
 await create(page);await page.locator('[data-id="bme280"]').click();await page.getByLabel('Connection bme280 VCC').selectOption('5V');await page.getByRole('button',{name:'Close inspector'}).click();
 const edge=page.locator('[data-id="wire:bme280:VCC"]');const point=await edge.locator('.react-flow__edge-path').evaluate((el:SVGPathElement)=>{const p=el.getPointAtLength(el.getTotalLength()*.7),m=el.getScreenCTM()!;return{x:p.x*m.a+p.y*m.c+m.e,y:p.x*m.b+p.y*m.d+m.f};});await page.mouse.click(point.x,point.y);
 await expect(page.locator('.cable-shine')).toHaveCount(1);await expect(page.locator('.wire-endpoints')).toContainText('ESP32 · 5V');await expect(page.locator('.wire-endpoints')).toContainText('Pin VCC');await expect(page.locator('.wire-validation')).toContainText('Local preview rejects this wiring');await expect(page.locator('.wire-validation')).toContainText('voltage_current_power');await expect(page.getByRole('button',{name:/Run practice/})).toBeDisabled();
 await page.emulateMedia({reducedMotion:'reduce'});expect(await page.locator('.cable-shine').evaluate(e=>getComputedStyle(e).animationName)).toBe('none');await page.getByRole('button',{name:'Close inspector'}).click();await expect(page.locator('.cable-shine')).toHaveCount(0);
});
