import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {Store} from '../services/api/store.js';
import {Engine} from '../services/api/engine.js';
import {createGoldenContract} from '../packages/component-catalog/index.js';
const agent={plan:async()=>({plan:{supported:true,recipe:'esp32-room-monitor' as const,buttonPin:27,ledPin:26,title:'Room monitor',summary:'Golden test',sda:21,scl:22,sensorAddress:118,displayAddress:60,steps:['Wire'],clarification:''},route:{testDouble:true},provider:'test double'}),diagnose:async()=>({diagnosis:{category:'communication' as const,summary:'No I2C device observed',checks:['Power off; GPIO21 to SDA'],repair:'Reconnect SDA with power off',retryAllowed:true},route:{testDouble:true},provider:'test double'})};
const knowledge={retrieve:async()=>({status:'unavailable' as const,backend:'test double',query:'test',hits:[],error:'mock'}),remember:async()=>({status:'unavailable' as const,backend:'test double',error:'mock'}),url:'mock',request:async()=>({})};
test('persistent golden failure/recovery and immutable evidence',async()=>{const dir=mkdtempSync(join(tmpdir(),'iot-test-')),file=join(dir,'db.sqlite');let store=new Store(file);const engine=new Engine(store,agent,knowledge);const p=engine.create('Build ESP32 BME280 OLED');await engine.plan(p.id);assert.equal(engine.project(p.id).status,'ready');const normal=await engine.run(p.id,'simulation');assert.equal(normal.status,'SIMULATED_VERIFIED');assert.equal(normal.physical,false);const broken=await engine.run(p.id,'simulation','sda');assert.equal(broken.status,'FAILED');const failed=engine.project(p.id);assert.equal(failed.repairs.length,1);assert.equal(failed.failures.length,1);const repaired=await engine.run(p.id,'simulation','none',undefined,broken.experimentId);assert.equal(repaired.status,'SIMULATED_VERIFIED');const full=engine.project(p.id);assert.equal(full.experiments[1].status,'FAILED');assert.equal(full.experiments[2].parentId,broken.experimentId);assert.equal(full.observations.length,18);const identity=full.experiments[2].identity,rows=full.observations.filter((o:any)=>o.evidence.experimentId===identity.experimentId).map((o:any)=>o.evidence);store.db.prepare('UPDATE observations SET payload=? WHERE id=?').run(JSON.stringify({...full.observations[12],artifact:{hash:'tampered',body:{}}}),rows[0].id);assert.equal(engine.verifyStored(p.id,full.contracts[0].contract,identity,rows).passed,false);store.close();store=new Store(file);assert.equal(store.list('experiments',p.id).length,3);assert.equal(store.list('repairs',p.id).length,1);assert.equal(store.events(p.id).filter(e=>e.type==='verification.completed').length,3);assert.throws(()=>store.update('contracts',full.contracts[0]),/Immutable/);store.close();rmSync(dir,{recursive:true});});
test('unsupported prompt does not silently become golden build',async()=>{const store=new Store(':memory:');const unsupported={...agent,plan:async()=>({...await agent.plan(),plan:{...await agent.plan().then(r=>r.plan),supported:false,clarification:'Unsupported actuator'}})};const engine=new Engine(store,unsupported,knowledge);const p=engine.create('Build a mains relay robot');await engine.plan(p.id);assert.equal(engine.project(p.id).status,'clarification');assert.equal(engine.project(p.id).contracts.length,0);await assert.rejects(engine.run(p.id,'simulation'));store.close();});
test('missing stored artifact never passes evidence verifier',async()=>{const store=new Store(':memory:');const engine=new Engine(store,agent,knowledge);const contract=createGoldenContract();assert.equal(engine.verifyStored('unknown',contract,{experimentId:'unknown',nonce:'x',contractHash:'0'.repeat(64),firmwareHash:'0'.repeat(64)},[]).passed,false);store.close();});
test('physical request rejects simulated executor provenance',async()=>{const store=new Store(':memory:');const runtime={invoke:async()=>({source:'simulation',checks:[],simulated:true}),detect:async()=>({devices:[]})};const engine=new Engine(store,agent,knowledge,runtime);const p=engine.create('Build ESP32 BME280 OLED');await engine.plan(p.id);await assert.rejects(engine.run(p.id,'physical','none','/dev/test'),/provenance/);assert.equal(engine.project(p.id).verifications.length,0);assert.equal(engine.project(p.id).status,'error');assert.equal(engine.ports.size,0);store.close();});
test('replan increments canonical contract version and restart terminates orphan runs',async()=>{const store=new Store(':memory:');const engine=new Engine(store,agent,knowledge);const p=engine.create('Build ESP32 BME280 OLED');await engine.plan(p.id);await engine.plan(p.id);assert.deepEqual(store.list('contracts',p.id).map(c=>[c.version,c.contract.version]),[[1,1],[2,2]]);store.insert('experiments',p.id,{id:'orphan',status:'running'});engine.change(p.id,{status:'running'});new Engine(store,agent,knowledge);assert.equal(store.get('experiments','orphan').status,'ERROR');assert.equal(store.get('projects',p.id).status,'error');assert.equal(store.list('failures',p.id).length,1);assert.ok(store.events(p.id).some(e=>e.type==='experiment.interrupted'));store.close();});
test('two projects cannot share one physical port while executor is active',async()=>{const store=new Store(':memory:');let release:(value:any)=>void=()=>{};const runtime={invoke:()=>new Promise<any>(resolve=>{release=resolve;}),detect:async()=>({devices:[]})};const engine=new Engine(store,agent,knowledge,runtime);const first=engine.create('Build ESP32 BME280 OLED'),second=engine.create('Build ESP32 BME280 OLED');await engine.plan(first.id);await engine.plan(second.id);const pending=engine.run(first.id,'physical','none','/dev/shared');await assert.rejects(engine.run(second.id,'physical','none','/dev/shared'),/already in use/);release({source:'physical',checks:[],rawSerial:[]});await pending;assert.equal(engine.ports.size,0);store.close();});

test('setup transaction failure releases project and USB locks',async()=>{
 const store=new Store(':memory:');const engine=new Engine(store,agent,knowledge);
 const project=engine.create('Build ESP32 BME280 OLED');await engine.plan(project.id);
 const transaction=store.transaction.bind(store);store.transaction=()=>{throw new Error('setup unavailable');};
 await assert.rejects(engine.run(project.id,'physical','none','/dev/setup'),/setup unavailable/);
 assert.equal(engine.busy.size,0);assert.equal(engine.ports.size,0);
 store.transaction=transaction;await engine.run(project.id,'simulation');
 assert.equal(engine.project(project.id).status,'SIMULATED_VERIFIED');store.close();
});
