import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {Engine} from '../services/api/engine.js';
import {Store} from '../services/api/store.js';
import {receiveRemoteJob,approveRemoteJob,reconcileRemoteJobs} from '../services/api/remote-jobs.js';
const plan={supported:true,recipe:'esp32-room-monitor' as const,buttonPin:27,ledPin:26,title:'Monitor',summary:'Pins revised',sda:21,scl:22,sensorAddress:118,displayAddress:60,steps:['Wire safely'],clarification:''};
const knowledge={retrieve:async()=>({status:'unavailable' as const,backend:'test',query:'',hits:[],error:'fixture'}),remember:async()=>({status:'unavailable' as const,backend:'test',error:'fixture'}),url:'test',request:async()=>({})};
function setup(){const store=new Store(':memory:');const agent={plan:async()=>({plan,route:{fixture:true},provider:'fixture'}),revise:async()=>({plan,route:{fixture:true},provider:'fixture'}),diagnose:async()=>({diagnosis:{category:'unknown' as const,summary:'Inspect observed logs',checks:[],repair:'Power off before inspection',retryAllowed:false},route:{fixture:true},provider:'fixture'})};const runtime={invoke:async()=>{throw new Error('toolchain unavailable');},detect:async()=>({devices:[],toolchain:false,available:false,backend:'test'})};return{store,engine:new Engine(store,agent,knowledge,runtime as any)};}
async function golden(engine:Engine){const created=engine.create('ESP32 BME280 OLED');await engine.plan(created.id);return engine.project(created.id);}
function job(p:any,over:Record<string,unknown>={}){const c=p.contracts.find((x:any)=>x.id===p.contractId);return{id:randomUUID(),leaseId:randomUUID(),expiresAt:Date.now()+25000,operation:'simulate',projectId:p.id,contractId:c.id,contractHash:c.hash,deviceId:null,...over};}
test('remote simulate job approves locally, runs bounded evidence and completes',async()=>{const {store,engine}=setup();const p=await golden(engine);const record=receiveRemoteJob(engine,job(p));assert.equal(record.status,'awaiting_approval');const done=await approveRemoteJob(engine,record.id);assert.equal(done.status,'completed');assert.equal(done.summary.status,'completed');assert.equal(done.summary.source,'simulation');assert.equal(done.summary.verification,'SIMULATED_VERIFIED');assert.equal(done.summary.checks.length,6);assert.equal(done.summary.artifactHashes.length,6);assert.equal(engine.project(p.id).experiments.length,1);store.close();});
test('duplicate remote submission is idempotent and identity mismatch is refused',async()=>{const {store,engine}=setup();const p=await golden(engine);const input=job(p);const first=receiveRemoteJob(engine,input);const again=receiveRemoteJob(engine,{...input});assert.equal(again.id,first.id);assert.throws(()=>receiveRemoteJob(engine,{...input,leaseId:randomUUID()}),/identity mismatch/);store.close();});
test('expired windows, contract mismatches and planning-only drafts are refused',async()=>{const {store,engine}=setup();const p=await golden(engine);assert.throws(()=>receiveRemoteJob(engine,job(p,{expiresAt:Date.now()-1000})),/expired/);assert.throws(()=>receiveRemoteJob(engine,job(p,{contractHash:'0'.repeat(64)})),/version mismatch/);(engine.agent as any).revise=async()=>({plan:{...plan,supported:false,clarification:'Distance recipe unavailable'},route:{},provider:'fixture'});await engine.chat(p.id,{message:'distance alarm',purpose:'design',expectedContractId:p.contractId,expectedDraftId:null});assert.equal(engine.project(p.id).activeDesign.status,'planning_only');assert.throws(()=>receiveRemoteJob(engine,job(engine.project(p.id))),/planning only/);store.close();});
test('physical remote job needs matching device and failed execution never replays',async()=>{const {store,engine}=setup();const p=await golden(engine);const record=receiveRemoteJob(engine,job(p,{operation:'physical',deviceId:'/dev/cu.usb-serial'}));await assert.rejects(approveRemoteJob(engine,record.id,'/dev/cu.other'),/differs from remote request/);const failed=await approveRemoteJob(engine,record.id,'/dev/cu.usb-serial');assert.equal(failed.status,'failed');assert.equal(engine.project(p.id).experiments.at(-1).status,'ERROR');await assert.rejects(approveRemoteJob(engine,record.id,'/dev/cu.usb-serial'),/already handled/);store.close();});
test('reconcile fails interrupted running jobs without replay',async()=>{const {store,engine}=setup();const p=await golden(engine);const running={id:randomUUID(),input:job(p),status:'running',createdAt:new Date().toISOString()};store.insert('remote_jobs',p.id,running);reconcileRemoteJobs(engine);const after=store.get('remote_jobs',running.id);assert.equal(after.status,'failed');assert.match(after.summary.message,/not replayed/);store.close();});
