import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {rm} from 'node:fs/promises';
import {resolve} from 'node:path';
import {executeRuntime,normalizeDevices,parseObservationFrames} from '../runtime/local-bridge/mcp-executor.js';
import {RuntimeRequestSchema} from '../packages/runtime-client/index.js';
const source='#include <Wire.h>\nvoid setup() {}\nvoid loop() {}';
const request=RuntimeRequestSchema.parse({action:'run',authorized:true,port:'/dev/cu.test',experimentId:'adapter-test-'+process.pid,nonce:'fresh',contractHash:'a'.repeat(64),firmwareHash:createHash('sha256').update(source).digest('hex'),source,fqbn:'esp32:esp32:esp32',safetyContext:{board:'esp32-devkit',fqbn:'esp32:esp32:esp32',wiring:[{pin:'21',signalType:'i2c',direction:'bidirectional',voltage:3.3}],power:{supplyVoltage:5,supplyThrough:'usb'}}});
if(request.action!=='run')throw new Error('Test request');
test('serial requires matching nonce and contract identity; malformed lines never establish proof',()=>{const frame={marker:'iot_observation',experimentId:request.experimentId,contractHash:request.contractHash,nonce:request.nonce,cycle:1,check:'sensor_readings',passed:true,data:{temperature:25,humidity:50}};assert.equal(parseObservationFrames(JSON.stringify({...frame,nonce:'stale'}),request).handshake,false);assert.equal(parseObservationFrames(JSON.stringify({...frame,contractHash:'b'.repeat(64)}),request).handshake,false);const result=parseObservationFrames('boot\n'+JSON.stringify(frame)+'\nmalformed',request);assert.equal(result.handshake,true);assert.equal(result.checks[0].check,'sensor_readings');});
test('USB candidate is independent from upstream inferred board confidence',()=>{const ports=normalizeDevices({data:{ports:[{address:'/dev/cu.test',protocol:'serial',hardwareId:'USB VID:PID=10C4:EA60',properties:[{name:'vid',value:'10C4'}],selectedFqbn:'arduino:avr:uno'},{address:'/dev/cu.network',protocol:'network',properties:[]},{address:'/dev/cu.unknown',protocol:'serial',selectedFqbn:'esp32:esp32:esp32',properties:[]}]}});assert.equal(ports.length,2);assert.equal(ports[0].candidate,true);assert.equal(ports[1].candidate,false);});
test('adapter preserves failed compilation and never uploads after failure',async()=>{const names:string[]=[];try{const result=await executeRuntime(request,async(name,args)=>{names.push(name);if(name==='arduino_cli_doctor')return{ok:true,data:{installed:true}};if(name==='detect_hardware')return{ok:true,data:{ports:[{address:request.port,protocol:'serial',properties:[{name:'vid',value:'10c4'}]}]}};assert.equal(name,'compile_sketch');assert.equal(args.exportBinaries,true);assert.equal(args.autoInstallCore,false);assert.equal(args.buildPath,undefined);return{ok:false,raw:{stderr:'compiler failed'}};});assert.equal((result as any).source,'physical');assert.equal((result as any).runtimeError,'firmware_compile');assert.deepEqual(names,['arduino_cli_doctor','detect_hardware','compile_sketch']);assert.equal((result as any).checks[0].passed,false);}finally{await rm(resolve('.runtime/builds',request.experimentId),{recursive:true,force:true});}});
test('digest mismatch refuses compilation',async()=>{const names:string[]=[];await assert.rejects(executeRuntime({...request,firmwareHash:'b'.repeat(64)},async(name)=>{names.push(name);return name==='arduino_cli_doctor'?{ok:true,data:{installed:true}}:{ok:true,data:{ports:[]}};}),/Firmware digest mismatch/);assert.ok(!names.includes('compile_sketch'));});
test('physical path uses enforced preflight and retains bound telemetry despite expected monitor timeout',async()=>{const calls:string[]=[];try{const result:any=await executeRuntime(request,async(name,args)=>{calls.push(name);if(name==='arduino_cli_doctor')return{ok:true,data:{installed:true}};if(name==='detect_hardware')return{ok:true,data:{ports:[{address:request.port,protocol:'serial',properties:[]}]},raw:{stdout:JSON.stringify({detected_ports:[{port:{address:request.port,properties:{vid:'0x10c4',pid:'0xea60'}}}]})}};if(name==='compile_sketch')return{ok:true};if(name==='upload_sketch'){assert.equal(args.unsafeSkipPreflight,false);assert.equal(args.autoInstallCore,false);assert.deepEqual(args.safetyContext,request.safetyContext);return{ok:true};}assert.equal(name,'read_serial_snapshot');assert.equal(args.baudRate,115200);const identity={marker:'iot_observation',experimentId:request.experimentId,contractHash:request.contractHash,nonce:request.nonce,cycle:1};return{ok:true,raw:{timedOut:true,stdout:['device_addresses','sensor_readings','oled_initialized'].map(check=>JSON.stringify({...identity,check,passed:true,data:{observed:true}})).join('\n')}};});assert.deepEqual(calls,['arduino_cli_doctor','detect_hardware','compile_sketch','upload_sketch','read_serial_snapshot']);assert.equal(result.checks.length,6);assert.equal(result.checks[0].passed,true);assert.equal(result.rawSerial.length,3);assert.equal(result.toolLogs.length,5);}finally{await rm(resolve('.runtime/builds',request.experimentId),{recursive:true,force:true});}});

const observation=(cycle:unknown,check:string,passed=true)=>JSON.stringify({marker:'iot_observation',experimentId:request.experimentId,contractHash:request.contractHash,nonce:request.nonce,cycle,check,passed,data:{observed:passed}});
test('checks never combine passing observations from different cycles',()=>{
 const serial=[observation(1,'device_addresses',false),observation(1,'sensor_readings'),observation(1,'oled_initialized',false),observation(2,'device_addresses'),observation(2,'sensor_readings',false),observation(2,'oled_initialized')].join('\n');
 const result=parseObservationFrames(serial,request);assert.equal(result.handshake,true);assert.equal(result.checks.length,3);assert.equal(result.checks.find(c=>c.check==='sensor_readings')?.passed,false);
});
test('latest incomplete cycle cannot reuse prior successful checks or delayed older frames',()=>{
 const serial=[...['device_addresses','sensor_readings','oled_initialized'].map(check=>observation(1,check)),observation(2,'device_addresses'),observation(2,'sensor_readings'),observation(1,'oled_initialized')].join('\n');
 const result=parseObservationFrames(serial,request);assert.deepEqual(result.checks.map(c=>c.check),['device_addresses','sensor_readings']);assert.equal(result.rawSerial.length,6);
});
test('missing or malformed cycle and unknown check cannot establish board handshake',()=>{
 for(const cycle of [undefined,null,0,-1,1.5,'1',Number.MAX_SAFE_INTEGER+1]){const result=parseObservationFrames(observation(cycle,'sensor_readings'),request);assert.equal(result.handshake,false);assert.deepEqual(result.checks,[]);}
 assert.equal(parseObservationFrames(observation(1,'unknown'),request).handshake,false);
 assert.equal(parseObservationFrames('null\nmalformed',request).handshake,false);
});
test('conflicting duplicate check fails the cycle and cannot be overwritten by success',()=>{
 const result=parseObservationFrames([observation(1,'sensor_readings'),observation(1,'sensor_readings',false),observation(1,'sensor_readings')].join('\n'),request);
 assert.equal(result.checks[0].passed,false);assert.equal(result.checks[0].data.error,'conflicting_cycle_observations');
 const identical=parseObservationFrames([observation(1,'sensor_readings'),observation(1,'sensor_readings')].join('\n'),request);assert.equal(identical.checks[0].passed,true);
});
