import {test} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {Store} from '../services/api/store.js';
import {SiteEngine,projectDeviceStatus} from '../services/api/site-engine.js';
import {createGoldenContract} from '../packages/component-catalog/index.js';
import {contractHash} from '../packages/evidence/index.js';
import {validateContract} from '../packages/validator/index.js';
const uid=()=>randomUUID();
const area=()=>({id:uid(),name:'Field',icon:'field' as const,position:{x:0,y:0}});
const device=(areaId:string,projectId:string|null=null)=>({id:uid(),name:'Monitor',kind:'environment' as const,areaId,required:true,projectId,position:{x:20,y:135}});
function project(store:Store){const id=uid(),recordId=uid(),contract=createGoldenContract(id);store.insert('projects',id,{id,contractId:recordId});store.insert('contracts',id,{id:recordId,hash:contractHash(contract),contract,validation:validateContract(contract)});return{id,recordId,hash:contractHash(contract)};}
function run(store:Store,p:ReturnType<typeof project>,mode='physical',status='VERIFIED',physical=true){const id=uid();store.insert('experiments',p.id,{id,contractId:p.recordId,identity:{experimentId:id,contractHash:p.hash},mode,status});store.insert('verifications',p.id,{id:uid(),experimentId:id,mode,status,passed:true,physical});return id;}
test('site CAS, integrity, occupied deletion and reopen preserve independent project artifacts',()=>{const dir=mkdtempSync(join(tmpdir(),'iot-sites-')),path=join(dir,'site.sqlite');let store=new Store(path);const engine=new SiteEngine(store),p=project(store),a=area(),b=area(),d=device(a.id,p.id),contractBefore=JSON.stringify(store.list('contracts'));const s=engine.create({name:'Farm',areas:[a,b],devices:[d],links:[]});assert.throws(()=>engine.update(s.id,{expectedRevision:9,snapshot:{name:'Bad',areas:[],devices:[],links:[]}}),/revision conflict/);assert.equal(engine.get(s.id).revision,0);assert.throws(()=>engine.update(s.id,{expectedRevision:0,snapshot:{name:'Farm',areas:[b],devices:[],links:[]}}),/occupied area/);assert.throws(()=>engine.create({name:'Bad',areas:[a],devices:[d,{...d,id:uid()}],links:[]}),/already attached/);assert.throws(()=>engine.create({name:'Bad',areas:[a],devices:[{...d,projectId:uid()}],links:[]}),/project not found/);assert.throws(()=>engine.create({name:'Bad',areas:[a],devices:[{...d,position:{x:Infinity,y:0}}],links:[]}));assert.throws(()=>engine.create({name:'Bad',areas:[a],devices:[d],links:[{id:uid(),source:d.id,target:d.id,kind:'wifi',status:'declared_unverified'}]}),/endpoints/);const updated=engine.update(s.id,{expectedRevision:0,snapshot:{name:'Farm',areas:[b],devices:[{...d,areaId:b.id}],links:[]}});assert.equal(updated.revision,1);assert.equal(JSON.stringify(store.list('contracts')),contractBefore);store.close();store=new Store(path);assert.equal(new SiteEngine(store).get(s.id).devices[0].areaId,b.id);store.close();rmSync(dir,{recursive:true});});
test('latest overall experiment, current contract, executable draft and matching verdict govern device status',()=>{const store=new Store(':memory:'),p=project(store);run(store,p);assert.equal(projectDeviceStatus(store,p.id),'physical_verified');const next=run(store,p,'simulation','SIMULATED_VERIFIED',false);assert.equal(projectDeviceStatus(store,p.id),'simulated_verified');store.insert('verifications',p.id,{id:uid(),experimentId:next,mode:'simulation',status:'SIMULATED_VERIFIED',passed:false,physical:false});assert.equal(projectDeviceStatus(store,p.id),'unverified');run(store,p,'physical','FAILED',false);assert.equal(projectDeviceStatus(store,p.id),'failed');const q=project(store);store.update('projects',{id:p.id,contractId:q.recordId});assert.equal(projectDeviceStatus(store,p.id),'unverified');store.insert('design_drafts',p.id,{id:uid(),status:'planning_only',contractId:q.recordId});assert.equal(projectDeviceStatus(store,p.id),'blocked');store.close();});
test('aggregate needs nonempty required physical set; simulation, planning and optional devices never supply proof',()=>{const store=new Store(':memory:'),engine=new SiteEngine(store),a=area(),p=project(store),q=project(store);run(store,p);run(store,q,'simulation','SIMULATED_VERIFIED',false);assert.equal(engine.create({name:'Empty',areas:[a],devices:[],links:[]}).status,'unverified');assert.equal(engine.create({name:'Optional',areas:[a],devices:[{...device(a.id,p.id),required:false}],links:[]}).status,'unverified');const s=engine.create({name:'Mixed',areas:[a],devices:[device(a.id,p.id),device(a.id,q.id)],links:[]});assert.equal(s.status,'unverified');assert.equal(s.areaStatuses[a.id],'unverified');assert.equal(engine.create({name:'Physical',areas:[a],devices:[device(a.id,p.id),{...device(a.id),required:false}],links:[]}).status,'physical_verified');assert.equal(projectDeviceStatus(store,null),'planning');store.close();});

test('status refuses mismatched identity and spoofed physical flags',()=>{const store=new Store(':memory:'),p=project(store),id=run(store,p);store.update('experiments',{...store.get('experiments',id),identity:{experimentId:id,contractHash:'wrong'}});assert.equal(projectDeviceStatus(store,p.id),'unverified');run(store,p,'simulation','VERIFIED',true);assert.equal(projectDeviceStatus(store,p.id),'unverified');store.close();});
