import {HardwareLibraryBrowser} from './hardware-library';
import {useState} from 'react';
import {post} from './api';
export function HardwareChat({project,onRefresh,blocked=false}:{project:any;onRefresh:()=>Promise<void>;blocked?:boolean}) {
 const [message,setMessage]=useState(''),[purpose,setPurpose]=useState<'design'|'debug'>('design'),[pending,setPending]=useState(false),[error,setError]=useState('');
 async function send(){if(!message.trim()||pending||project.busy||blocked)return;setPending(true);setError('');try{await post(`/projects/${project.id}/chat`,{message:message.trim(),purpose,expectedContractId:project.contractId??null,expectedDraftId:project.activeDesign?.id??null});setMessage('');}catch(e){setError((e as Error).message);}finally{await onRefresh();setPending(false);}}
 return <section className="hardware-chat"><span className="school-eyebrow">AI HARDWARE ENGINEER</span><h2>Ngomong, lalu kita rangkai.</h2><div className="chat-history" role="log" aria-live="polite">{!(project.chatMessages?.length)&&<p>Ceritakan alat yang kamu mau. Untuk koreksi, pilih “Periksa hasil” agar AI memakai bukti eksperimen terbaru.</p>}{project.chatMessages?.map((m:any)=><div className={'chat-message '+m.role} key={m.id}><strong>{m.role==='user'?'Kamu':'Hardware engineer'}</strong><p>{m.message}</p>{m.experimentId&&<small>Bukti eksperimen {m.experimentId.slice(0,8)}</small>}</div>)}</div><form onSubmit={e=>{e.preventDefault();send();}}><label htmlFor="chat-purpose">Tujuan percakapan</label><select id="chat-purpose" value={purpose} disabled={pending||project.busy||blocked} onChange={e=>setPurpose(e.target.value as 'design'|'debug')}><option value="design">Buat / ubah rancangan</option><option value="debug">Periksa hasil & keluhan</option></select><label htmlFor="hardware-message">Pesan untuk hardware engineer</label><textarea id="hardware-message" value={message} maxLength={2000} rows={4} onChange={e=>setMessage(e.target.value)} placeholder="Ganti SDA ke GPIO18. Atau: sensor belum terbaca, tolong periksa log."/><small>Pesan diproses provider AI untuk membantu build. Riwayat chat disimpan lokal, tidak otomatis jadi memory bersama.</small><button className="school-primary" disabled={!message.trim()||pending||project.busy||blocked}>{pending?'Menyusun rancangan…':'Kirim pesan'}</button>{error&&<p role="alert">{error}</p>}</form></section>;
}
export function ComponentCatalog({catalog,project,onRefresh,blocked=false}:{catalog:any[];project:any;onRefresh:()=>Promise<void>;blocked?:boolean}) {
 const [tab,setTab]=useState<'parts'|'reference'>('parts');
 const [search,setSearch]=useState(''),[pending,setPending]=useState(false),[error,setError]=useState('');
 const selected:string[]=project.activeDesign?.componentIds??project.contracts.find((v:any)=>v.id===project.contractId)?.contract.components.map((c:any)=>c.manifest.id)??[];
 async function change(componentId:string,operation:'add'|'remove'){setPending(true);setError('');try{await post(`/projects/${project.id}/components`,{componentId,operation,expectedContractId:project.contractId??null,expectedDraftId:project.activeDesign?.id??null});}catch(e){setError((e as Error).message);}finally{await onRefresh();setPending(false);}}
 return <section className="catalog-library"><div className="catalog-tabs" aria-label="Pilih katalog"><button aria-pressed={tab==='parts'} onClick={()=>setTab('parts')}>Komponen draft</button><button aria-pressed={tab==='reference'} onClick={()=>setTab('reference')}>Pustaka IoT</button></div>{tab==='reference'?<HardwareLibraryBrowser/>:<><h3>Semua komponen</h3>{blocked&&<p role="status">Terapkan atau buang edit kabel sebelum mengubah katalog.</p>}<label htmlFor="catalog-search">Cari asset</label><input id="catalog-search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Sensor, LED, tombol…"/><small>Drag asset ke area draft, atau gunakan tombol Tambah.</small><div className="catalog-items">{catalog.filter(c=>(c.name+' '+c.id).toLowerCase().includes(search.toLowerCase())).map(c=><div className="catalog-item" key={c.id} draggable={!pending&&!project.busy&&!blocked} onDragStart={e=>e.dataTransfer.setData('application/x-iot-component',c.id)}><span className="catalog-category">{c.protocol==='i2c'?'Sensor & layar I2C':'Input & output digital'}</span><strong>{c.name}</strong><small>{c.support==='golden'?'Resep executable':'Referensi perencanaan'}</small><button disabled={pending||project.busy||blocked} onClick={()=>change(c.id,selected.includes(c.id)?'remove':'add')}>{selected.includes(c.id)?'Hapus':'Tambah'}</button></div>)}</div><div className="catalog-drop" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const cid=e.dataTransfer.getData('application/x-iot-component');if(!pending&&!project.busy&&!blocked&&catalog.some(c=>c.id===cid))change(cid,'add');}}><strong>Drop komponen untuk draft</strong><p>{selected.map(cid=>catalog.find(c=>c.id===cid)?.name??cid).join(' + ')||'Belum ada komponen'}</p><small>Setelah memilih, minta chat menyusun ulang wiring dan firmware.</small></div>{error&&<p role="alert">{error}</p>}</>}</section>;
}
