import {useEffect,useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import {ArrowUpRightIcon,ArrowRightIcon,CircuitryIcon,CpuIcon,DownloadSimpleIcon} from '@phosphor-icons/react';
import {BoardDrawing} from '../../../packages/ui-hardware/index';
import {mountLandingMotion} from './landing-motion';
import './landing-new.css';
const releases='https://github.com/dansya-arsana/iot-ai-id/releases/tag/v0.1.0-preview.1';
const partnership='/partnership-brief.txt';
function Brand(){return <Link to="/" className="rl-brand" aria-label="iot.ai.id beranda"><CircuitryIcon size={24} weight="bold"/>iot.ai.id</Link>;}
export function Landing(){
 const root=useRef<HTMLDivElement>(null),header=useRef<HTMLElement>(null),menuButton=useRef<HTMLButtonElement>(null);const[menu,setMenu]=useState(false);
 useEffect(()=>root.current?mountLandingMotion(root.current):undefined,[]);
 useEffect(()=>{const outside=(e:PointerEvent)=>{if(e.target instanceof Node&&!header.current?.contains(e.target))setMenu(false);};const escape=(e:KeyboardEvent)=>{if(e.key==='Escape'&&menu){setMenu(false);menuButton.current?.focus();}};document.addEventListener('pointerdown',outside);document.addEventListener('keydown',escape);return()=>{document.removeEventListener('pointerdown',outside);document.removeEventListener('keydown',escape);};},[menu]);
 return <div ref={root} className="result-landing">
  <div className="rl-loader" role="status" aria-label="Menyiapkan halaman"><span><CircuitryIcon size={36}/>iot.ai.id</span><div className="rl-loader-track"><i/></div><small>DARI IDE. KE DUNIA NYATA.</small></div>
  <a className="rl-skip" href="#landing-main">Lewati ke konten</a><header ref={header} className="rl-header" data-enter><Brand/><nav className="rl-desktop-nav" aria-label="Navigasi utama"><Link to="/hardware">Hardware</Link><Link to="/learn">Belajar</Link><a href="#komunitas">Komunitas</a></nav><a className="rl-header-download" href={releases}>Desktop <DownloadSimpleIcon size={16}/></a><button ref={menuButton} className="rl-menu-toggle" aria-expanded={menu} aria-controls="landing-menu" onClick={()=>setMenu(!menu)}>{menu?'Tutup':'Menu'}</button>{menu&&<nav id="landing-menu" className="rl-mobile-nav" aria-label="Navigasi mobile"><Link onClick={()=>setMenu(false)} to="/hardware">Hardware</Link><Link onClick={()=>setMenu(false)} to="/learn">Belajar</Link><a onClick={()=>setMenu(false)} href="#komunitas">Komunitas</a><a href={releases}>Unduh desktop</a></nav>}</header>
  <main id="landing-main" tabIndex={-1}>
   <section className="rl-hero" aria-labelledby="landing-title" lang="en"><img className="rl-capsule" data-enter src="/assets/landing/hero-capsule.png" alt="Concept render: a robotic hand holding an ESP32 board inside a glass test capsule" width="1024" height="1024" fetchPriority="high"/><div className="rl-hero-copy"><p className="rl-eyebrow" data-enter>INDONESIA · REAL-WORLD HARDWARE VERIFICATION</p><h1 id="landing-title" aria-label="Testing robots and sensors where the real world is messy.">{['Testing robots','and sensors where','the world is messy.'].map(line=><span className="rl-line" key={line}>{line.split(' ').map((word,i)=><span data-enter key={i}>{word}&nbsp;</span>)}</span>)}</h1><p className="rl-hero-description" data-enter>Heat, humidity, unstable power and field conditions. Turned into verifiable evidence for robotics and AI teams.</p><a className="rl-button rl-button-dark" data-enter href={partnership} download>Explore field testing <ArrowRightIcon size={18}/></a></div><div className="rl-specimens">{[{code:'FN-01',label:'Field telemetry node',img:'card-field-node'},{code:'TS-01',label:'Tactile sensor module',img:'card-tactile'}].map(c=><figure className="rl-specimen" data-enter key={c.code}><img src={`/assets/landing/${c.img}.png`} alt={`Concept render: ${c.label.toLowerCase()}`} width="768" height="1024" loading="lazy"/><figcaption><b>{c.code}</b><span>{c.label}</span></figcaption></figure>)}</div><div className="rl-hero-bottom"><span>CONCEPT RENDERS · NOT AVAILABLE PRODUCTS</span><a href="#kemungkinan">SCROLL ↓</a></div></section>
   <section id="kemungkinan" className="rl-section rl-possibilities"><div className="rl-section-intro" data-reveal><p className="rl-eyebrow">01 / KEMUNGKINAN KECIL, DAMPAK NYATA</p><h2>Mulai dari masalah<br/>di sekitar kamu.</h2><p>Komponen menjadi berguna saat punya tujuan. Pilih satu kebutuhan, lalu cari cara untuk mengukurnya.</p></div><div className="rl-example-grid">{[{n:'01',title:'Ruangan lebih nyaman.',text:'Bayangkan pemantau suhu dan kelembapan untuk memahami kondisi ruang belajar.',part:'ESP32 + sensor lingkungan',icon:'°C',to:'/hardware/bme280'},{n:'02',title:'Jarak jadi informasi.',text:'Eksplorasi sensor jarak untuk membaca ruang, batas, atau posisi sebuah benda.',part:'Sensor jarak + mikrokontroler',icon:'↔',to:'/hardware'},{n:'03',title:'Gerakan punya respons.',text:'Pelajari bagaimana sensor gerak dapat memicu lampu atau memberi tanda aktivitas.',part:'Sensor gerak + output',icon:'◎',to:'/hardware'}].map(item=><Link data-reveal to={item.to} key={item.n} className="rl-example"><div className="rl-example-art"><span>{item.icon}</span><small>KONSEP / {item.n}</small><div className="rl-circuit-lines"/></div><div className="rl-example-copy"><small>{item.part}</small><h3>{item.title}</h3><p>{item.text}</p><span>Kenali komponennya <ArrowUpRightIcon size={18}/></span></div></Link>)}</div><p className="rl-concept-note">Contoh konsep untuk eksplorasi. Hasil pada perangkat fisik perlu dirangkai dan diuji.</p></section>
   <section className="rl-section rl-path"><div data-reveal><p className="rl-eyebrow">02 / DARI KENAL KE BISA</p><h2>Satu ide.<br/>Langkah yang jelas.</h2><Link to="/learn" className="rl-text-link">Mulai belajar <ArrowRightIcon/></Link><figure className="rl-board-reference"><BoardDrawing/><figcaption>Contoh rangkaian monitor ruangan. Visual referensi, bukan hasil uji fisik.</figcaption></figure></div><div className="rl-path-steps">{[['Kenali hardware.','Baca fungsi, spesifikasi, dan batas komponen sebelum memilih.'],['Rangkai dengan tujuan.','Hubungkan kebutuhan dengan sensor, kontrol, dan output yang tepat.'],['Uji. Catat. Perbaiki.','Bandingkan hasil dengan tujuan. Simpan apa yang bekerja dan apa yang belum.']].map(([title,text],i)=><article data-reveal key={title}><span>0{i+1}</span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></section>
   <section id="komunitas" className="rl-section rl-community"><div data-reveal><p className="rl-eyebrow">03 / DIBANGUN BERSAMA</p><h2>Tempat ide bertemu<br/>orang yang mau mencoba.</h2></div><div className="rl-community-copy" data-reveal><p>Untuk maker yang penasaran, sekolah yang belajar melalui praktik, dan engineer yang ingin berbagi cara kerja.</p><p>Mari bangun pengetahuan dari eksperimen yang terdokumentasi: tujuan, rangkaian, hasil uji, dan pelajaran berikutnya.</p><a className="rl-button" href="https://github.com/dansya-arsana/iot-ai-id">Ikut membangun <ArrowUpRightIcon size={20}/></a><span>Proyek terbuka. Kontribusi dimulai dari satu ide yang jelas.</span></div></section>
   <section className="rl-section rl-supplier" lang="en"><div data-reveal><p className="rl-eyebrow">FOR HARDWARE SUPPLIERS & MANUFACTURERS</p><h2>Bring your hardware<br/>to builders in Indonesia.</h2></div><div data-reveal><p>Help makers, schools, and engineers understand what your hardware can do. Let's explore useful documentation, learning projects, and reproducible experiments together.</p><a className="rl-button rl-button-white" href={partnership} download>Explore a partnership <ArrowUpRightIcon size={20}/></a><a className="rl-text-link" href="/partnership-brief.txt" download>Download partnership brief <DownloadSimpleIcon size={18}/></a><small>Partnership opportunities. No supplier affiliation is implied.</small></div></section>
   <section className="rl-section rl-final" data-reveal><p className="rl-eyebrow">IDE BERIKUTNYA MULAI DI SINI</p><h2>Apa yang ingin<br/>kamu buat berguna?</h2><div><Link className="rl-button" to="/hardware">Temukan hardware <CpuIcon size={20}/></Link><Link className="rl-text-link" to="/learn">Pelajari langkah pertama <ArrowUpRightIcon size={20}/></Link></div></section>
  </main><footer className="rl-footer"><div><Brand/><p>Dari komponen. Jadi sesuatu yang berguna.</p></div><nav aria-label="Navigasi footer"><Link to="/hardware">Hardware</Link><Link to="/learn">Belajar</Link><a href={releases}>Desktop</a><a href="https://github.com/dansya-arsana/iot-ai-id">GitHub</a></nav><div className="rl-footer-bottom"><span>INDONESIA · IDE YANG BISA DISENTUH.</span><Link to="/docs">Dokumentasi <ArrowUpRightIcon size={14}/></Link></div></footer>
 </div>;
}
