import {createContext,useContext,useEffect,useRef,useState,type ReactNode} from 'react';
import {api,post} from './api';
import type {SiteView,SiteSnapshot} from '../../../packages/site-contract';
import {farmProfiles} from '../../../packages/application-catalog';
export const siteIcons={field:'🌾',greenhouse:'🌿',building:'⌂',tank:'◉'};
export function siteSnapshot(site:SiteView):SiteSnapshot{return {name:site.name,areas:site.areas,devices:site.devices,links:site.links};}
type Workspace={site:SiteView;projects:any[];areaId?:string;activeDeviceId:string;selected:string;setSelected:(id:string)=>void;focus:(id:string)=>void;dirty:boolean;setDirty:(dirty:boolean)=>void;save:(next:SiteSnapshot)=>Promise<boolean>;saving:boolean;conflict:boolean;error:string;gesture:(working:boolean)=>void;reload:()=>void;refreshProjects:()=>Promise<void>};
const Context=createContext<Workspace|null>(null);
export function useSiteWorkspace(){return useContext(Context);}
export function SiteIntentChat(){
 const workspace=useSiteWorkspace()!;
 const [message,setMessage]=useState(''),[pending,setPending]=useState(false),[error,setError]=useState('');
 const pendingRef=useRef(false);
 async function send(){
  if(pendingRef.current||workspace.saving||workspace.conflict||message.trim().length<8)return;
  pendingRef.current=true;setPending(true);setError('');workspace.gesture(true);
  try{
   const project=await post('/projects',{goal:message.trim(),entryPoint:'build'});
   const next=siteSnapshot(workspace.site),active=next.devices.find(d=>d.id===workspace.activeDeviceId);
   if(active)next.devices=next.devices.map(d=>d.id===active.id?{...d,projectId:project.id}:d);
   else{
    const areaId=next.areas[0]?.id??crypto.randomUUID();
    if(!next.areas.length)next.areas=[{id:areaId,name:'Area utama',icon:'building',position:{x:40,y:40}}];
    next.devices=[...next.devices,{id:crypto.randomUUID(),name:'Perangkat pertama',kind:'custom',areaId,required:true,projectId:project.id,position:{x:30,y:90}}];
   }
   if(!await workspace.save(next))throw new Error('Proyek '+project.id+' dibuat, tetapi belum tertaut. Pilih proyek tersebut melalui Area.');
   await workspace.refreshProjects();workspace.reload();setMessage('');
  }catch(e){setError((e as Error).message);}finally{workspace.gesture(false);pendingRef.current=false;setPending(false);}
 }
 return <section className="hardware-chat"><span className="school-eyebrow">AI HARDWARE ENGINEER</span><h2>Ceritakan perangkatmu.</h2><div className="chat-history"><p>Canvas ini bisa menampung beberapa area dan perangkat. Mulai dengan satu perangkat, lalu tambahkan area melalui toolbar.</p></div><form onSubmit={e=>{e.preventDefault();void send();}}><label htmlFor="site-intent">Pesan untuk hardware engineer</label><textarea id="site-intent" value={message} onChange={e=>setMessage(e.target.value)} maxLength={2000} rows={4} placeholder="Buat monitor suhu ESP32 dengan BME280 dan OLED."/><small>Rancangan yang belum didukung tetap menjadi draft perencanaan.</small><button disabled={pending||workspace.saving||workspace.conflict||message.trim().length<8}>{pending?'Menyusun rancangan…':'Kirim pesan'}</button>{error&&<p role="alert">{error}</p>}</form></section>;
}
export function SiteWorkspace({siteId,areaId,initialProjectId,children}:{siteId:string;areaId?:string;initialProjectId?:string;children:(projectId:string|null)=>ReactNode}){
 const [site,setSite]=useState<SiteView>(),[projects,setProjects]=useState<any[]>([]),[activeDeviceId,setActive]=useState(''),[selected,setSelected]=useState(''),[dirty,setDirty]=useState(false),[saving,setSaving]=useState(false),[conflict,setConflict]=useState(false),[error,setError]=useState(''),[reloadKey,setReload]=useState(0);
 const liveSite=useRef<SiteView|undefined>(undefined),working=useRef(false),writing=useRef(false),conflicted=useRef(false),dirtyRef=useRef(false);
 useEffect(()=>{dirtyRef.current=dirty;},[dirty]);
 async function refreshProjects(){const list=await api('/projects');const linked=new Set(liveSite.current?.devices.map(d=>d.projectId).filter(Boolean));const full=await Promise.all(list.projects.map((p:any)=>linked.has(p.id)?api('/projects/'+p.id):Promise.resolve(p)));setProjects(full);}
 useEffect(()=>{let live=true;const load=async()=>{try{const s=await api<SiteView>('/sites/'+siteId);if(!live||dirtyRef.current||working.current||writing.current||conflicted.current||liveSite.current&&s.revision<liveSite.current.revision)return;liveSite.current=s;setSite(s);setActive(old=>s.devices.some(d=>d.id===old)?old:(s.devices.find(d=>d.projectId===initialProjectId)?.id??s.devices.find(d=>(!areaId||d.areaId===areaId)&&d.projectId)?.id??s.devices.find(d=>!areaId||d.areaId===areaId)?.id??''));}catch(e){if(live)setError((e as Error).message);}};void load();const timer=setInterval(load,3000);return()=>{live=false;clearInterval(timer);};},[siteId,areaId,initialProjectId,reloadKey]);
 useEffect(()=>{let live=true;const load=async()=>{try{const list=await api('/projects');const linked=new Set(liveSite.current?.devices.map(d=>d.projectId).filter(Boolean));const full=await Promise.all(list.projects.map((p:any)=>linked.has(p.id)?api('/projects/'+p.id):Promise.resolve(p)));if(live)setProjects(full);}catch(e){if(live)setError((e as Error).message);}};void load();const timer=setInterval(load,3000);return()=>{live=false;clearInterval(timer);};},[siteId,site?.revision]);
 async function save(next:SiteSnapshot){const current=liveSite.current;if(!current||writing.current||conflicted.current||dirtyRef.current){working.current=false;return false;}writing.current=true;setSaving(true);setError('');try{const result=await api<SiteView>('/sites/'+siteId,{method:'PUT',body:JSON.stringify({expectedRevision:site!.revision,snapshot:next})});liveSite.current=result;setSite(result);setActive(old=>result.devices.some(d=>d.id===old)?old:(result.devices.find(d=>(!areaId||d.areaId===areaId)&&d.projectId)?.id??result.devices.find(d=>!areaId||d.areaId===areaId)?.id??''));setSelected(old=>result.areas.some(a=>a.id===old)||result.devices.some(d=>d.id===old)||result.links.some(l=>l.id===old)?old:'');return true;}catch(e){const message=(e as Error).message;if(message.includes('revision conflict')){conflicted.current=true;setConflict(true);}setError(message+' · Perubahan belum disimpan. Muat ulang untuk revisi terbaru.');return false;}finally{working.current=false;writing.current=false;setSaving(false);}}
 function focus(id:string){if(dirtyRef.current){setError('Apply wiring atau Buang edit sebelum memilih perangkat lain.');return;}if(writing.current)return;setActive(id);setSelected(id);setError('');}
 function reload(){if(dirtyRef.current){setError('Apply wiring atau Buang edit sebelum memuat ulang.');return;}conflicted.current=false;setConflict(false);working.current=false;liveSite.current=undefined;setError('');setReload(k=>k+1);}
 if(!site)return <main className="sites-page"><p role={error?'alert':undefined}>{error||'Memuat meja kerja…'}</p></main>;
 const active=site.devices.find(d=>d.id===activeDeviceId);
 return <Context.Provider value={{site,projects,areaId,activeDeviceId,selected,setSelected,focus,dirty,setDirty:value=>{dirtyRef.current=value;setDirty(value);},save,saving,conflict,error,gesture:value=>{working.current=value;},reload,refreshProjects}}>{children(active?.projectId??null)}</Context.Provider>;
}
export function SiteDrawer({onClose}:{onClose:()=>void}){
 const workspace=useSiteWorkspace()!;const {site,projects,selected,save,saving,conflict,dirty}=workspace;
 const [areaName,setAreaName]=useState(''),[areaIcon,setAreaIcon]=useState<keyof typeof siteIcons>('field'),[deviceName,setDeviceName]=useState(''),[deviceArea,setDeviceArea]=useState(''),[kind,setKind]=useState<any>('environment'),[projectId,setProjectId]=useState(''),[required,setRequired]=useState(true),[source,setSource]=useState(''),[target,setTarget]=useState(''),[linkKind,setLinkKind]=useState<any>('wifi'),[intent,setIntent]=useState(''),[creating,setCreating]=useState(false),[createError,setCreateError]=useState('');
 const creatingRef=useRef(false);
 const area=site.areas.find(a=>a.id===selected),device=site.devices.find(d=>d.id===selected),link=site.links.find(l=>l.id===selected),blocked=saving||conflict||dirty||creating;
 const changeDevice=(patch:Partial<SiteSnapshot['devices'][number]>)=>save({...siteSnapshot(site),devices:site.devices.map(d=>d.id===selected?{...d,...patch}:d)});
 async function createProject(){if(!device||blocked||creatingRef.current||intent.trim().length<8)return;creatingRef.current=true;workspace.gesture(true);setCreating(true);setCreateError('');try{const p=await post('/projects',{goal:intent,entryPoint:'build'});if(!await changeDevice({projectId:p.id}))setCreateError('Proyek '+p.id+' dibuat, tetapi penautan gagal. Pilih dari daftar setelah memuat ulang.');await workspace.refreshProjects();}catch(e){setCreateError((e as Error).message);}finally{creatingRef.current=false;workspace.gesture(false);setCreating(false);}}
 return <aside className="flow-site-drawer" aria-label="Lokasi & area"><button className="flow-close" onClick={onClose} aria-label="Tutup area">×</button><h2>Lokasi & area</h2><button disabled={blocked} onClick={()=>{let x=40;const areas=site.areas.map(a=>{const width=Math.max(1100,...site.devices.filter(d=>d.areaId===a.id).map(d=>d.position.x+980));const next={...a,position:{x,y:40}};x+=width+100;return next;});void save({...siteSnapshot(site),areas});}}>Rapikan area</button><button disabled={blocked} onClick={()=>save({...siteSnapshot(site),devices:site.devices.map(d=>({...d,position:{x:30+site.devices.filter(other=>other.areaId===d.areaId).findIndex(other=>other.id===d.id)*950,y:90}}))})}>Rapikan perangkat</button><p>{site.name} · revisi {site.revision}</p><button disabled={saving||dirty} onClick={workspace.reload}>Muat ulang</button>{workspace.error&&<p role="alert">{workspace.error}</p>}{createError&&<p role="alert">{createError}</p>}<fieldset disabled={blocked}><section className="site-device-list"><h3>Area & perangkat</h3>{site.areas.map(a=><article key={a.id}><button onClick={()=>workspace.setSelected(a.id)}>{siteIcons[a.icon]} {a.name}</button>{site.devices.filter(d=>d.areaId===a.id).map(d=><div key={d.id}><button onClick={()=>workspace.setSelected(d.id)}>{d.name} · {site.deviceStatuses[d.id]}</button><button onClick={()=>workspace.focus(d.id)} aria-pressed={workspace.activeDeviceId===d.id}>Fokus {d.name}</button></div>)}</article>)}</section>
 {area?<><h3>Inspector area</h3><label>Nama area<input key={area.id+area.name} defaultValue={area.name} onBlur={e=>{if(e.target.value!==area.name)void save({...siteSnapshot(site),areas:site.areas.map(a=>a.id===selected?{...a,name:e.target.value}:a)});}}/></label><label>Ikon area<select value={area.icon} onChange={e=>save({...siteSnapshot(site),areas:site.areas.map(a=>a.id===selected?{...a,icon:e.target.value as any}:a)})}>{Object.keys(siteIcons).map(k=><option key={k}>{k}</option>)}</select></label><button disabled={site.devices.some(d=>d.areaId===area.id)} onClick={()=>save({...siteSnapshot(site),areas:site.areas.filter(a=>a.id!==selected)})}>Hapus area kosong</button></>:device?<><h3>Inspector perangkat</h3><label>Nama perangkat<input key={device.id+device.name} defaultValue={device.name} onBlur={e=>{if(e.target.value!==device.name)void changeDevice({name:e.target.value});}}/></label><label>Area perangkat<select aria-label="Area perangkat" value={device.areaId} onChange={e=>changeDevice({areaId:e.target.value,position:{x:30,y:90}})}>{site.areas.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Jenis kebutuhan<select value={device.kind} onChange={e=>changeDevice({kind:e.target.value as any})}>{farmProfiles.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}<option value="custom">Lainnya</option></select></label><label><input type="checkbox" checked={device.required} onChange={e=>changeDevice({required:e.target.checked})}/> Wajib untuk verifikasi area</label><label>Proyek wiring<select value={device.projectId??''} onChange={e=>changeDevice({projectId:e.target.value||null})}><option value="">Perencanaan tanpa proyek</option>{projects.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label><button onClick={()=>workspace.focus(device.id)}>Fokus perangkat</button><label>Intent proyek baru<textarea value={intent} onChange={e=>setIntent(e.target.value)} maxLength={2000} placeholder={farmProfiles.find(p=>p.id===device.kind)?.goal}/></label><button disabled={intent.trim().length<8} onClick={createProject}>Buat proyek dari intent & tautkan</button><button onClick={()=>save({...siteSnapshot(site),devices:site.devices.filter(d=>d.id!==selected),links:site.links.filter(l=>l.source!==selected&&l.target!==selected)})}>Lepas perangkat dari lokasi</button></>:link?<><h3>Koneksi logis</h3><p>{link.kind.toUpperCase()} · deklarasi belum terverifikasi</p><button onClick={()=>save({...siteSnapshot(site),links:site.links.filter(l=>l.id!==selected)})}>Hapus deklarasi</button></>:<p>Pilih area atau perangkat pada canvas.</p>}
 {(area||device)&&<form key={selected} onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget),position={x:Number(data.get('x')),y:Number(data.get('y'))};if(device)void changeDevice({position});else void save({...siteSnapshot(site),areas:site.areas.map(a=>a.id===selected?{...a,position}:a)});}}><h3>Posisi · keyboard</h3><label>X<input name="x" type="number" min="-10000" max="10000" defaultValue={(area??device)!.position.x}/></label><label>Y<input name="y" type="number" min="-10000" max="10000" defaultValue={(area??device)!.position.y}/></label><button>Simpan posisi</button></form>}
 <form onSubmit={async e=>{e.preventDefault();if(await save({...siteSnapshot(site),areas:[...site.areas,{id:crypto.randomUUID(),name:areaName,icon:areaIcon,position:{x:site.areas.length*1200,y:40}}]}))setAreaName('');}}><label>Nama lokasi<input key={site.name} defaultValue={site.name} maxLength={100} onBlur={e=>{if(e.target.value!==site.name)void save({...siteSnapshot(site),name:e.target.value});}}/></label><h3>Tambah area</h3><label>Nama area baru<input required value={areaName} onChange={e=>setAreaName(e.target.value)} maxLength={100}/></label><label>Ikon<select value={areaIcon} onChange={e=>setAreaIcon(e.target.value as keyof typeof siteIcons)}>{Object.keys(siteIcons).map(k=><option key={k}>{k}</option>)}</select></label><button>Tambah area</button></form>
 <form onSubmit={async e=>{e.preventDefault();const areaId=deviceArea||site.areas[0]?.id;if(!areaId)return;if(await save({...siteSnapshot(site),devices:[...site.devices,{id:crypto.randomUUID(),name:deviceName,kind,areaId,required,projectId:projectId||null,position:{x:30+site.devices.filter(d=>d.areaId===areaId).length*950,y:90}}]}))setDeviceName('');}}><h3>Tambah perangkat</h3><label>Nama perangkat baru<input required value={deviceName} onChange={e=>setDeviceName(e.target.value)} maxLength={100}/></label><label>Area baru<select aria-label="Area baru" value={deviceArea||site.areas[0]?.id||''} onChange={e=>setDeviceArea(e.target.value)}>{!site.areas.length&&<option value="">Pilih area</option>}{site.areas.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Kebutuhan<select value={kind} onChange={e=>setKind(e.target.value)}>{farmProfiles.map(p=><option key={p.id} value={p.id}>{p.name} · perencanaan</option>)}<option value="custom">Lainnya</option></select></label><p>{farmProfiles.find(p=>p.id===kind)?.needs}</p><label>Proyek yang ditautkan<select value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">Tanpa proyek · perencanaan</option>{projects.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label><label><input type="checkbox" checked={required} onChange={e=>setRequired(e.target.checked)}/> Perangkat wajib</label><button disabled={!site.areas.length}>Tambah perangkat</button></form>
 <form onSubmit={e=>{e.preventDefault();void save({...siteSnapshot(site),links:[...site.links,{id:crypto.randomUUID(),source,target,kind:linkKind,status:'declared_unverified'}]});}}><h3>Deklarasi jaringan</h3><label>Dari<select aria-label="Dari" required value={source} onChange={e=>setSource(e.target.value)}><option value="">Pilih perangkat</option>{site.devices.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>Ke<select aria-label="Ke" required value={target} onChange={e=>setTarget(e.target.value)}><option value="">Pilih perangkat</option>{site.devices.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>Protokol<select aria-label="Protokol" value={linkKind} onChange={e=>setLinkKind(e.target.value)}>{['wifi','mqtt','ethernet','lora'].map(k=><option key={k}>{k}</option>)}</select></label><button>Tambah deklarasi</button><small>Garis jaringan adalah deklarasi, belum terbukti. Kabel GPIO hanya di dalam satu perangkat.</small></form>
 </fieldset></aside>;
}
