import {createElement,useEffect,useRef,useState} from 'react';
import '@wokwi/elements/dist/esm/esp32-devkit-v1-element.js';
import '@wokwi/elements/dist/esm/ssd1306-element.js';
import type {HardwareContract} from '../hardware-contract/index';
type PinElement=HTMLElement&{pinInfo:{name:string;x:number;y:number}[];updateComplete:Promise<boolean>};
export function BoardDrawing({broken=false,contract,large=false,selectedComponent,onSelectComponent}:{broken?:boolean;contract?:HardwareContract;large?:boolean;selectedComponent?:string;onSelectComponent?:(id:string)=>void}){
 const container=useRef<HTMLDivElement>(null),board=useRef<PinElement>(null),display=useRef<PinElement>(null);
 const[anchors,setAnchors]=useState<Record<string,{x:number;y:number}>>({});
 const sda=contract?.connections.find(w=>w.role==='sda')?.boardPin??'21',scl=contract?.connections.find(w=>w.role==='scl')?.boardPin??'22';
 useEffect(()=>{let active=true;const measure=()=>{if(!active||!container.current||!board.current||!display.current)return;const root=container.current.getBoundingClientRect(),result:Record<string,{x:number;y:number}>={};for(const [prefix,element,width,height] of [['board',board.current,107,201],['display',display.current,150,116]] as const){const rect=element.getBoundingClientRect();for(const pin of element.pinInfo)result[prefix+':'+pin.name]={x:(rect.left-root.left+pin.x*rect.width/width)*600/root.width,y:(rect.top-root.top+pin.y*rect.height/height)*410/root.height};}setAnchors(result);};Promise.all([board.current?.updateComplete,display.current?.updateComplete]).then(measure);const observer=new ResizeObserver(measure);if(container.current)observer.observe(container.current);return()=>{active=false;observer.disconnect();};},[sda,scl]);
 const cables=[{name:'3V3',from:'3V3',to:'3V3',color:'#ba3030'},{name:'GND',from:'GND.1',to:'GND',color:'#333'},{name:'SDA',from:'D'+sda,to:'DATA',color:'#158567'},{name:'SCL',from:'D'+scl,to:'CLK',color:'#b17920'}];
 const isGolden = !contract || contract.components.every(c=>['bme280','ssd1306'].includes(c.manifest.id));
 if (contract && !isGolden) {
  return <div className={'board-drawing oss-drawing'+(large?' large':'')}><div className="drawing-label mono">HARDWARE CONTRACT / WIRING</div><table className="oss-wire-table" aria-label="Tabel sambungan kontrak"><thead><tr><th>Komponen</th><th>Pin</th><th>ESP32</th></tr></thead><tbody>{contract.connections.map((w,i)=><tr key={i}><td>{w.componentId}</td><td>{w.pin}</td><td className="mono">{w.boardPin.startsWith('G')?w.boardPin:['3V3','GND'].includes(w.boardPin)?w.boardPin:'GPIO'+w.boardPin}</td></tr>)}</tbody></table><table className="oss-wire-table" aria-label="Bagian dalam assembly"><thead><tr><th>Assembly</th><th>Bagian</th><th>Jalur</th></tr></thead><tbody>{contract.components.flatMap(c=>c.manifest.assembly?c.manifest.assembly.parts.map(part=><tr key={c.manifest.id+part.ref}><td>{c.manifest.id}</td><td>{part.ref} · {part.kind} {part.value}</td><td className="mono">{c.manifest.assembly!.nets.filter(n=>n.terminals.some(t=>t.startsWith(part.ref))).map(n=>n.name).join(', ')}</td></tr>):[])}</tbody></table><div className="drawing-footer mono"><span>RANGKAIAN NYATA PER ASSEMBLY</span><span>3.3V LOGIC</span></div><span className="drawing-caption mono">TEXUAL WIRING · RAKIT DENGAN DAYA MATI · BUKAN VISUAL RANGKAIAN</span></div>;
 }
 return <div className={'board-drawing oss-drawing'+(large?' large':'')}><div className="drawing-label mono">{contract?'HARDWARE CONTRACT / WIRING':'GOLDEN BUILD / REFERENCE'}</div><div className="oss-circuit" ref={container}>{createElement('wokwi-esp32-devkit-v1',{ref:board,className:'oss-esp', 'aria-label':'ESP32 DevKit reference visual'})}{createElement('wokwi-ssd1306',{ref:display,className:'oss-oled','aria-label':'SSD1306 reference breakout visual'})}<div className="oss-sensor"><strong>BME280</strong><span>MANIFEST / I2C</span><code>0x{(contract?.expected.devices.find(d=>d.componentId==='bme280')?.address??118).toString(16)}</code><span>VCC · GND · SDA · SCL</span></div>{onSelectComponent&&<div className="school-board-targets">{[{id:contract?.board.id??'esp32-devkit',label:'ESP32 DevKit',className:'esp'},{id:'ssd1306',label:'SSD1306 OLED',className:'oled'},{id:'bme280',label:'BME280',className:'sensor'}].map(part=><button key={part.id} className={part.className} aria-label={'Pilih '+part.label} aria-pressed={selectedComponent===part.id} onClick={()=>onSelectComponent(part.id)}/>)}</div>}<svg className="oss-wires" viewBox="0 0 600 410" preserveAspectRatio="none" aria-label="Contract pin connections">{cables.map((c,i)=>{const a=anchors['board:'+c.from],b=anchors['display:'+c.to];if(!a||!b)return null;const lane=235+i*17;return <g key={c.name} className={'wire-'+c.name}><title>{`Kabel ${c.name}${c.name==='SDA'?` ke GPIO${sda} — barat ini ${broken?'terputus pada latihan kegagalan':'tersambung'}`:c.name==='SCL'?` ke GPIO${scl}`:''}`}</title><path className="wire-path" d={`M ${a.x} ${a.y} H ${lane} V ${b.y-24-i*7} H ${b.x} V ${b.y}`} fill="none" stroke={c.color} strokeWidth="2.5" strokeDasharray={broken&&c.name==='SDA'?'6 9':undefined}/><text x={20+i*145} y={390} fill={c.color}>{c.name}{c.name==='SDA'?' / GPIO'+sda:c.name==='SCL'?' / GPIO'+scl:''}</text><path d={`M ${lane} ${b.y-24-i*7} V ${310+i*12} H 354`} fill="none" stroke={c.color} strokeWidth="2" strokeDasharray="3 4"/></g>;})}</svg></div><div className="drawing-footer mono"><span>WOKWI ELEMENTS / VISUAL ONLY</span><span>3.3V LOGIC</span></div><span className="drawing-caption mono">REFERENCE BREAKOUT · INSPECT ACTUAL PIN LABELS · NOT TELEMETRY</span></div>;
}
