import { z } from 'zod';
function isCatalogUri(uri:unknown):uri is string {
 if(typeof uri!=='string'||/[?#\\]/.test(uri))return false;
 try{const decoded=decodeURIComponent(uri);if(/[?#\\]/.test(decoded)||decoded.split('/').some(segment=>segment==='.'||segment==='..'))return false;return decoded==='viking://resources/iot-ai-id/hardware-catalog'||decoded.startsWith('viking://resources/iot-ai-id/hardware-catalog/');}catch{return false;}
}
const envelope=z.object({status:z.string(),result:z.any().optional(),error:z.any().optional()});
export class OpenVikingKnowledge {
 readonly url=process.env.OPENVIKING_URL??'http://127.0.0.1:1933';
 async request(path:string,options:RequestInit={}){const response=await fetch(this.url+path,{...options,headers:{...(process.env.OPENVIKING_API_KEY?{'X-API-Key':process.env.OPENVIKING_API_KEY}:{}),...options.headers},signal:AbortSignal.timeout(20000)});const data=envelope.parse(await response.json());if(!response.ok||data.status!=='ok')throw new Error(`Knowledge service ${response.status}: ${data.error?.code??'unavailable'}`);return data.result;}
 async retrieve(query:string,scope:'workspace'|'catalog'='workspace'){try{const result=await this.request('/api/v1/search/find',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query,target_uri:scope==='catalog'?'viking://resources/iot-ai-id/hardware-catalog':'viking://resources/iot-ai-id',limit:5})});const hits=scope==='catalog'?(result.resources??[]).filter((hit:any)=>isCatalogUri(hit.uri)):[...(result.resources??[]),...(result.memories??[])];const texts=await Promise.all(hits.map(async (hit:any)=>{try{const content=await this.request('/api/v1/content/read?uri='+encodeURIComponent(hit.uri));return {uri:hit.uri,score:hit.score,text:String(content?.content??content).slice(0,6000)};}catch{return {uri:hit.uri,score:hit.score,text:hit.abstract??''};}}));return{status:'live' as const,backend:'OpenViking',query,hits:texts,retrievedAt:new Date().toISOString()};}catch(error){return{status:'unavailable' as const,backend:'OpenViking',query,hits:[],error:error instanceof Error?error.message:'Knowledge unavailable'};}}
 async remember(name:string,text:string){try{const file=new Blob([text],{type:'text/markdown'});const form=new FormData();form.append('file',file,name+'.md');const upload=await this.request('/api/v1/resources/temp_upload',{method:'POST',body:form});const added=await this.request('/api/v1/resources',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({temp_file_id:upload.temp_file_id,to:'viking://resources/iot-ai-id/'+name,create_parent:true,processing_mode:'vectors_only',wait:true})});if(added.task_id){for(let i=0;i<60;i++){const task=await this.request('/api/v1/tasks/'+encodeURIComponent(added.task_id));if(task.status==='completed')return{status:'stored' as const,backend:'OpenViking',uri:added.root_uri??'viking://resources/iot-ai-id/'+name,taskId:added.task_id};if(['failed','cancelled'].includes(task.status))throw new Error('Knowledge indexing failed');await new Promise(resolve=>setTimeout(resolve,500));}throw new Error('Knowledge indexing is still pending');}return{status:'stored' as const,backend:'OpenViking',uri:added.root_uri??'viking://resources/iot-ai-id/'+name};}catch(error){return{status:'unavailable' as const,backend:'OpenViking',error:error instanceof Error?error.message:'Knowledge unavailable'};}}
}
