import type {BoardManifest,ComponentManifest,HardwareContract} from '../hardware-contract/index.js';
const espSource='https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/peripherals/gpio.html';
export const esp32Devkit:BoardManifest={id:'esp32-devkit',name:'ESP32 DevKit (WROOM-32)',mcu:'ESP32',logicVoltage:3.3,powerRails:{'3V3':3.3,'5V':5},maxPeripheralCurrentMa:100,pins:[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,21,22,23,25,26,27,32,33,34,35,36,39].map(n=>({name:String(n),capabilities:n>=34?['input','analog']:['input','output','i2c','spi','uart',...([32,33,25,26,27,0,2,4,12,13,14,15].includes(n)?['analog' as const]:[])],reserved:(n>=6&&n<=11)||n===1||n===3,strapping:[0,2,5,12,15].includes(n)})),sources:[espSource,'https://docs.espressif.com/projects/esp-dev-kits/en/latest/esp32/esp32-devkitc/user_guide.html']};
function i2c(id:string,name:string,address:number,library:string,source:string,currentMa=10):ComponentManifest{return{id,name,voltage:[3.3,3.3],logicVoltage:3.3,currentMa,protocol:'i2c',pins:[{name:'VCC',role:'power',required:true},{name:'GND',role:'ground',required:true},{name:'SDA',role:'sda',required:true},{name:'SCL',role:'scl',required:true}],addresses:[address],libraries:[library],quirks:['Use a 3.3V-compatible breakout; pull-ups must connect to 3.3V. Verify the exact module pinout.'],sources:[source],support:['bme280','ssd1306'].includes(id)?'golden':'planning_only',reviewStatus:'specification_only'};}
export const components:ComponentManifest[]=[
i2c('bme280','BME280 environmental sensor',0x76,'Adafruit BME280 Library','https://cdn-shop.adafruit.com/product-files/2652/2652.pdf',5),
i2c('ssd1306','SSD1306 128×64 OLED',0x3c,'Adafruit SSD1306','https://learn.adafruit.com/monochrome-oled-breakouts',30),
i2c('bmp280','BMP280 pressure sensor',0x76,'Adafruit BMP280 Library','https://www.bosch-sensortec.com/products/environmental-sensors/pressure-sensors/bmp280/'),
i2c('sht31','SHT31 temperature/humidity',0x44,'Adafruit SHT31 Library','https://sensirion.com/products/catalog/SHT31-DIS-B'),
i2c('aht20','AHT20 temperature/humidity',0x38,'Adafruit AHTX0','https://learn.adafruit.com/adafruit-aht20'),
i2c('bh1750','BH1750 light sensor',0x23,'BH1750','https://www.rohm.com/products/sensors-mems/ambient-light-sensor-ics/bh1750fvi-product'),
i2c('veml7700','VEML7700 light sensor',0x10,'Adafruit VEML7700 Library','https://www.vishay.com/docs/84286/veml7700.pdf'),
i2c('mpu6050','MPU6050 IMU',0x68,'Adafruit MPU6050','https://learn.adafruit.com/mpu6050-6-dof-accelerometer-and-gyro'),
i2c('lis3dh','LIS3DH accelerometer',0x18,'Adafruit LIS3DH','https://www.st.com/resource/en/datasheet/lis3dh.pdf'),
i2c('ads1115','ADS1115 ADC',0x48,'Adafruit ADS1X15','https://www.ti.com/lit/ds/symlink/ads1115.pdf'),
i2c('ina219','INA219 current monitor',0x40,'Adafruit INA219','https://www.ti.com/lit/ds/symlink/ina219.pdf'),
i2c('ds3231','DS3231 RTC (3.3V module)',0x68,'RTClib','https://www.analog.com/media/en/technical-documentation/data-sheets/DS3231.pdf'),
{id:'led',name:'LED with 330Ω resistor',voltage:[3.3,3.3],logicVoltage:3.3,currentMa:4,protocol:'digital',pins:[{name:'ANODE',role:'input',required:true},{name:'GND',role:'ground',required:true}],addresses:[],libraries:[],quirks:['Series resistor mandatory; do not drive high-current loads from GPIO.'],sources:['https://learn.adafruit.com/adafruit-arduino-lesson-2-leds/leds'],support:'planning_only',reviewStatus:'specification_only'},
{id:'button-pullup-10k',name:'Button assembly · 10kΩ pull-up to 3.3V',voltage:[3.3,3.3],logicVoltage:3.3,currentMa:1,protocol:'digital',pins:[{name:'VCC',role:'power',required:true},{name:'GND',role:'ground',required:true},{name:'SIGNAL',role:'output',required:true}],addresses:[],libraries:[],quirks:['Exact assembly: internal 10kΩ resistor between VCC and SIGNAL, switch between SIGNAL and GND. The board reads the switched node, never drive it.'],sources:['https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/peripherals/gpio.html'],support:'golden',reviewStatus:'specification_only',assembly:{parts:[{ref:'SW1',kind:'momentary-pushbutton',value:'SPST NO'},{ref:'R1',kind:'resistor',value:'10kΩ'}],nets:[{name:'vcc_pullup',terminals:['VCC','R1.1']},{name:'switched_node',terminals:['SIGNAL','R1.2','SW1.1']},{name:'switch_ground',terminals:['SW1.2','GND']}]}},
{id:'led-series-330',name:'LED assembly · 330Ω series resistor',voltage:[3.3,3.3],logicVoltage:3.3,currentMa:4,protocol:'digital',pins:[{name:'SIGNAL',role:'input',required:true},{name:'GND',role:'ground',required:true}],addresses:[],libraries:[],quirks:['Exact assembly: 330Ω series resistor between SIGNAL and the LED anode; LED cathode to GND. GPIO sources the resistor, never the bare LED.'],sources:['https://learn.adafruit.com/adafruit-arduino-lesson-2-leds/leds'],support:'golden',reviewStatus:'specification_only',assembly:{parts:[{ref:'LED1',kind:'led',value:'5mm diffuse'},{ref:'R2',kind:'resistor',value:'330Ω'}],nets:[{name:'gpio_series',terminals:['SIGNAL','R2.1']},{name:'resistor_anode',terminals:['R2.2','LED1.A']},{name:'cathode_ground',terminals:['LED1.K','GND']}]}},
{id:'button',name:'Momentary button with external 10kΩ pull-up',voltage:[3.3,3.3],logicVoltage:3.3,currentMa:1,protocol:'digital',pins:[{name:'SIGNAL',role:'output',required:true},{name:'GND',role:'ground',required:true}],addresses:[],libraries:[],quirks:['External pull-up to 3.3V required; debounce in firmware.'],sources:['https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/peripherals/gpio.html'],support:'planning_only',reviewStatus:'specification_only'}];
export const componentCatalog=components;
const mentionAliases:Record<string,string[]>={ssd1306:['oled']};
export function mentionedComponentIds(text:string):string[]{
 const lower=text.toLowerCase();
 return components.filter(c=>[c.id,...mentionAliases[c.id]??[]].some(term=>new RegExp(`\\b${term}\\b`).test(lower))).map(c=>c.id);
}
export function getComponent(id:string){return components.find(c=>c.id===id);}

export function createButtonLedContract(id='button-led',version=1):HardwareContract{return{recipe:{id:'esp32-button-led',version:1},schemaVersion:1,id,version,goal:'Build an ESP32 button-controlled LED with debounced input and verified behavior sequence.',board:structuredClone(esp32Devkit),components:['button-pullup-10k','led-series-330'].map(componentId=>({instanceId:componentId,manifest:structuredClone(getComponent(componentId)!)})),connections:[{componentId:'button-pullup-10k',pin:'VCC',boardPin:'3V3',role:'power'},{componentId:'button-pullup-10k',pin:'GND',boardPin:'GND',role:'ground'},{componentId:'button-pullup-10k',pin:'SIGNAL',boardPin:'27',role:'output',protocol:'digital' as const},{componentId:'led-series-330',pin:'SIGNAL',boardPin:'26',role:'input',protocol:'digital' as const},{componentId:'led-series-330',pin:'GND',boardPin:'GND',role:'ground'}],expected:{devices:[],valueRanges:{},serialMarkers:['iot_observation']},verification:{checks:['board_detected','compiled','flashed','button_input','output_commanded','behavior_sequence']},firmware:{framework:'arduino',fqbn:'esp32:esp32:esp32',libraries:[],generator:'button-led-v1'}};}

export function createGoldenContract(id='room-monitor',version=1):HardwareContract{return{schemaVersion:1,id,version,goal:'Build an ESP32 room monitor with temperature/humidity and an OLED.',board:structuredClone(esp32Devkit),components:['bme280','ssd1306'].map(instanceId=>({instanceId,manifest:structuredClone(getComponent(instanceId)!),address:getComponent(instanceId)!.addresses[0]})),connections:['bme280','ssd1306'].flatMap(componentId=>[{componentId,pin:'VCC',boardPin:'3V3',role:'power'},{componentId,pin:'GND',boardPin:'GND',role:'ground'},{componentId,pin:'SDA',boardPin:'21',role:'sda',protocol:'i2c' as const},{componentId,pin:'SCL',boardPin:'22',role:'scl',protocol:'i2c' as const}]),expected:{devices:[{componentId:'bme280',address:0x76},{componentId:'ssd1306',address:0x3c}],valueRanges:{temperature:[-40,85],humidity:[0,100]},serialMarkers:['iot_observation']},verification:{checks:['board_detected','compiled','flashed','device_addresses','sensor_readings','oled_initialized']},firmware:{framework:'arduino',fqbn:'esp32:esp32:esp32',libraries:['Adafruit BME280 Library','Adafruit SSD1306','Adafruit GFX Library','Adafruit Unified Sensor','Adafruit BusIO'],generator:'golden-v1'}};}
