import {HardwareReferenceSchema,filterHardwareLibrary,type HardwareReference,type HardwareLibraryFilter} from '../../packages/hardware-library/index.js';
import { DatabaseSync } from 'node:sqlite';
import { mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
export const tables = ['projects','contracts','agent_runs','firmware_artifacts','experiments','observations','failures','repairs','verifications','knowledge_receipts','human_actions','environment_records','rights_records','chat_messages','design_drafts','remote_jobs','sites'] as const;
export type Table = typeof tables[number];
export class Store {
 readonly db: DatabaseSync;
 constructor(path:string){if(path!==':memory:')mkdirSync(dirname(path),{recursive:true});this.db=new DatabaseSync(path);this.db.exec('PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;');for(const table of tables)this.db.exec(`CREATE TABLE IF NOT EXISTS ${table}(id TEXT PRIMARY KEY,project_id TEXT NOT NULL,payload TEXT NOT NULL,created_at TEXT NOT NULL)`);this.db.exec('CREATE TABLE IF NOT EXISTS hardware_catalog(id TEXT PRIMARY KEY,version INTEGER NOT NULL,payload TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)');this.db.exec('CREATE TABLE IF NOT EXISTS events(seq INTEGER PRIMARY KEY AUTOINCREMENT,project_id TEXT NOT NULL,type TEXT NOT NULL,payload TEXT NOT NULL,created_at TEXT NOT NULL)');}
 insert<T extends {id:string}>(table:Table, projectId:string,value:T){this.db.prepare(`INSERT INTO ${table}(id,project_id,payload,created_at) VALUES(?,?,?,?)`).run(value.id,projectId,JSON.stringify(value),new Date().toISOString());return value;}
 update<T extends {id:string}>(table:Table,value:T){if(table!=='projects'&&table!=='experiments'&&table!=='remote_jobs'&&table!=='sites')throw new Error('Immutable artifact');this.db.prepare(`UPDATE ${table} SET payload=? WHERE id=?`).run(JSON.stringify(value),value.id);return value;}
 get<T=any>(table:Table,id:string):T|undefined{const row=this.db.prepare(`SELECT payload FROM ${table} WHERE id=?`).get(id);return row?JSON.parse(row.payload as string):undefined;}
 list<T=any>(table:Table,projectId?:string):T[]{const rows=projectId?this.db.prepare(`SELECT payload FROM ${table} WHERE project_id=? ORDER BY created_at,rowid`).all(projectId):this.db.prepare(`SELECT payload FROM ${table} ORDER BY created_at DESC,rowid DESC`).all();return rows.map(row=>JSON.parse(row.payload as string));}
 event(projectId:string,type:string,payload:unknown){const now=new Date().toISOString();const result=this.db.prepare('INSERT INTO events(project_id,type,payload,created_at) VALUES(?,?,?,?)').run(projectId,type,JSON.stringify(payload),now);return {seq:Number(result.lastInsertRowid),type,payload,createdAt:now};}
 events(projectId:string,after=0){return this.db.prepare('SELECT seq,type,payload,created_at FROM events WHERE project_id=? AND seq>? ORDER BY seq').all(projectId,after).map(r=>({seq:r.seq,type:r.type,payload:JSON.parse(r.payload as string),createdAt:r.created_at}));}
 transaction<T>(fn:()=>T):T{this.db.exec('BEGIN IMMEDIATE');try{const value=fn();this.db.exec('COMMIT');return value;}catch(e){this.db.exec('ROLLBACK');throw e;}}
 seedHardwareLibrary(input:HardwareReference[]){const records=input.map(record=>HardwareReferenceSchema.parse(record));if(new Set(records.map(r=>r.id)).size!==records.length)throw new Error('Duplicate hardware reference identifier');return this.transaction(()=>{let inserted=0,updated=0;const now=new Date().toISOString();for(const record of records){const payload=JSON.stringify(record),old=this.db.prepare('SELECT payload FROM hardware_catalog WHERE id=?').get(record.id);if(!old){this.db.prepare('INSERT INTO hardware_catalog(id,version,payload,created_at,updated_at) VALUES(?,?,?,?,?)').run(record.id,record.version,payload,now,now);inserted++;}else if(old.payload!==payload){this.db.prepare('UPDATE hardware_catalog SET version=?,payload=?,updated_at=? WHERE id=?').run(record.version,payload,now,record.id);updated++;}}return{inserted,updated,total:records.length};});}
 hardwareLibrary(filter:HardwareLibraryFilter={}){const rows=this.db.prepare('SELECT payload FROM hardware_catalog ORDER BY id').all();return filterHardwareLibrary(rows.map(row=>HardwareReferenceSchema.parse(JSON.parse(row.payload as string))),filter);}
 hardwareReference(id:string){const row=this.db.prepare('SELECT payload FROM hardware_catalog WHERE id=?').get(id);return row?HardwareReferenceSchema.parse(JSON.parse(row.payload as string)):undefined;}
 close(){this.db.close();}
}
