import React,{useEffect,useState} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {ArrowUpRightIcon,PlusIcon} from '@phosphor-icons/react';
import {api,post} from '../api';
import {SiteHeader,SiteFooter} from '../site-shell';

const GOLDEN='Build an ESP32 room monitor with temperature/humidity and an OLED.';
const Header=()=><SiteHeader/>;
const Footer=()=><SiteFooter/>;
function PromptBox({compact=false}:{compact?:boolean}){const[goal,setGoal]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState('');const navigate=useNavigate();async function submit(event:React.FormEvent){event.preventDefault();setLoading(true);setError('');try{const p=await post('/projects',{goal:goal.trim()||GOLDEN,entryPoint:'build'});navigate('/project/'+p.id);}catch(e){setError(String((e as Error).message));setLoading(false);}}return <form className={'prompt-box'+(compact?' compact':'')} onSubmit={submit}><div className="prompt-head"><span className="mono">DESCRIBE YOUR BUILD</span><span className="mono subtle">ESP32 / V1</span></div><label className="sr-only" htmlFor={compact?'workspace-goal':'hero-goal'}>Hardware goal</label><textarea id={compact?'workspace-goal':'hero-goal'} value={goal} onChange={e=>setGoal(e.target.value)} placeholder="Build an ESP32 room monitor with temperature, humidity and an OLED…" maxLength={2000} rows={compact?3:2}/><div className="prompt-bottom"><button type="button" className="text-button example" onClick={()=>setGoal(GOLDEN)}><PlusIcon size={14}/> Use room monitor example</button><button className="button red" disabled={loading}>{loading?'Starting…':'Build it'} <ArrowUpRightIcon size={18}/></button></div><p className="prompt-disclosure">AI assistance processes the build goal and machine evidence. Keep personal data out. Research reuse is separate and excluded by default.</p>{error&&<p className="error" role="alert">{error}</p>}</form>;}
export function Build(){const[projects,setProjects]=useState<any[]>([]);const[error,setError]=useState('');useEffect(()=>{api('/projects').then(r=>setProjects(r.projects)).catch(e=>setError(e.message));},[]);return <div className="app-shell ds-app"><Header/><main className="build-start"><h1>What will<br/>you build?</h1><p>Describe a device. Inspect the plan. Test what’s real.</p><PromptBox/>{error&&<p className="error">{error}</p>}<section className="project-list"><div className="section-heading"><h2>Workbench</h2><span className="mono">{projects.length} PROJECTS</span></div>{projects.length?projects.map(p=><Link key={p.id} to={'/project/'+p.id}><div><strong>{p.title}</strong><p>{p.goal}</p></div><span className="badge">{p.status.replaceAll('_',' ')}</span><ArrowUpRightIcon/></Link>):<p className="empty-state">Your first experiment starts with a prompt.</p>}</section></main><Footer/></div>;}
